ALTER TABLE job_applications
    ADD CONSTRAINT chk_application_status
        CHECK (status IN (
                          'APPLIED', 'SCREENING', 'INTERVIEW',
                          'OFFER', 'REJECTED', 'WITHDRAWN'
            ));

CREATE TABLE application_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL,
    previous_status VARCHAR(30) NOT NULL,
    new_status VARCHAR(30) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_history_application
        FOREIGN KEY (application_id)
            REFERENCES job_applications(id),

    CONSTRAINT chk_history_previous_status
        CHECK (previous_status IN (
                                   'APPLIED', 'SCREENING', 'INTERVIEW',
                                   'OFFER', 'REJECTED', 'WITHDRAWN'
            )),

    CONSTRAINT chk_history_new_status
        CHECK (new_status IN (
                              'APPLIED', 'SCREENING', 'INTERVIEW',
                              'OFFER', 'REJECTED', 'WITHDRAWN'
            )),

    CONSTRAINT chk_history_status_changed
        CHECK (previous_status <> new_status)
);

CREATE INDEX idx_history_application_time
    ON application_status_history (application_id, changed_at, id);